// exmaple of redux re-usable constants
// export const DISPLAY_WELCOME_MSG = 'DISPLAY_WELCOME_MSG';
// export const RETRIEVE_MINIDASHBOARD_ENTRIES = 'RETRIEVE_MINIDASHBOARD_ENTRIES';

export const DISPLAY_WELCOME_CARD = 'DISPLAY_WELCOME_CARD';
export const DISPLAY_CARDS = 'DISPLAY_CARDS';
